import { Activity, ArrowRight, ArrowUpRight, ClipboardCheck, FileText, ShieldAlert, Sparkles, TriangleAlert } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Area, AreaChart, Bar, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { EmptyState, PageHeading, RiskBadge, StatusBadge } from '../components/Primitives.jsx';
import { riskColors, chartTooltipStyle } from '../charts/palette.js';
import { api } from '../services/api';

const tooltip = chartTooltipStyle;

export default function Dashboard() {
  const [data, setData] = useState(null);
  const [reports, setReports] = useState([]);
  const [error, setError] = useState('');
  useEffect(() => { Promise.all([api('/dashboard'), api('/reports')]).then(([summary, list]) => { setData(summary); setReports(list.slice(0, 5)); }).catch((err) => setError(err.message)); }, []);
  return <>
    <PageHeading eyebrow="WEDNESDAY, 30 SEPTEMBER 2026" title="Safety overview" description="A clearer view of what is happening across your reports." action={<Link to="/reports/new" className="button button-primary"><span>＋</span> Log a report</Link>} />
    {error && <div className="inline-error"><TriangleAlert size={16} />{error}</div>}
    <div className="summary-strip">{data ? <><b><span className="status-live" />Your demo workspace is up to date</b><span>Last activity <strong>just now</strong></span><span className="summary-source"><span />Synthetic Demo Data</span></> : <span>Loading workspace…</span>}</div>
    <section className="metric-grid"><Metric icon={FileText} label="Total reports" value={data?.totalReports} note="Across all locations" tone="mint" /><Metric icon={ShieldAlert} label="High-risk reports" value={data?.highRisk} note="High or critical rating" tone="coral" /><Metric icon={Sparkles} label="SIF precursors" value={data?.sifPrecursors} note="Prototype pattern matches" tone="amber" /><Metric icon={ClipboardCheck} label="Open actions" value={data?.openActions} note="Awaiting completion" tone="blue" /></section>
    <div className="dashboard-charts"><section className="panel trend-panel"><div className="panel-heading"><div><span className="eyebrow">REPORT ACTIVITY</span><h2>Signals over time</h2></div><div className="chart-legend"><span><i className="legend-reports" /> Reports</span><span><i className="legend-sif" /> SIF precursors</span></div></div>{data ? <div className="chart-area"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.trends} margin={{ top: 13, right: 7, left: -22, bottom: 0 }}><defs><linearGradient id="reportFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#168d79" stopOpacity={0.17} /><stop offset="95%" stopColor="#168d79" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#edf0ed" vertical={false} /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: '#87928a', fontSize: 11 }} dy={9} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fill: '#87928a', fontSize: 11 }} /><Tooltip contentStyle={tooltip} /><Area type="monotone" dataKey="reports" stroke="#168d79" strokeWidth={2.4} fill="url(#reportFill)" /><Area type="monotone" dataKey="precursors" stroke="#df654e" strokeWidth={2} strokeDasharray="5 4" fill="transparent" /></AreaChart></ResponsiveContainer></div> : <ChartLoading />}</section>
      <section className="panel severity-panel"><div className="panel-heading"><div><span className="eyebrow">RISK DISTRIBUTION</span><h2>By severity</h2></div><Link to="/reports" className="text-link">All reports <ArrowRight size={14} /></Link></div>{data ? <div className="severity-content"><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.severity} dataKey="value" nameKey="name" innerRadius={56} outerRadius={76} paddingAngle={3} stroke="none">{data.severity.map((item, index) => <Cell key={item.name} fill={riskColors[index]} />)}</Pie><Tooltip contentStyle={tooltip} /></PieChart></ResponsiveContainer><div className="donut-center"><strong>{data.totalReports}</strong><span>reports</span></div></div><div className="severity-legend">{data.severity.map((item, index) => <div key={item.name}><i style={{ background: riskColors[index] }} /><span>{item.name}</span><b>{item.value}</b></div>)}</div></div> : <ChartLoading />}</section></div>
    <div className="lower-grid"><section className="panel reports-panel"><div className="panel-heading"><div><span className="eyebrow">LATEST INTAKE</span><h2>Recent reports</h2></div><Link to="/reports" className="text-link">View report history <ArrowRight size={14} /></Link></div>{reports.length ? <div className="table-scroll"><table className="data-table"><thead><tr><th>REPORT</th><th>LOCATION</th><th>RISK</th><th>STATUS</th><th /></tr></thead><tbody>{reports.map((report) => <tr key={report.id}><td><Link className="report-name" to={`/reports/${report.id}`}>{report.title}<span>{report.id}</span></Link></td><td className="muted-cell">{report.location}</td><td><RiskBadge value={report.analysis.risk_level} /></td><td><StatusBadge value={report.status} /></td><td><Link className="row-arrow" to={`/reports/${report.id}`} aria-label={`Open ${report.title}`}><ArrowUpRight size={16} /></Link></td></tr>)}</tbody></table></div> : data ? <EmptyState title="No reports yet" detail="Submit a safety report to see it appear here." /> : <ChartLoading />}</section>
      <section className="panel alerts-panel"><div className="panel-heading"><div><span className="eyebrow">NEEDS A LOOK</span><h2>Signals & alerts</h2></div><span className="alert-count">{data?.alerts?.length || 0}</span></div>{data?.alerts?.length ? <div className="alert-list">{data.alerts.map((alert, index) => <div className={`alert-row alert-${alert.type}`} key={`${alert.type}-${index}`}><div className="alert-icon">{alert.type === 'critical' ? <ShieldAlert size={17} /> : alert.type === 'overdue' ? <ClipboardCheck size={17} /> : <Activity size={17} />}</div><div><b>{alert.title}</b><p>{alert.detail}</p></div><ArrowRight size={15} /></div>)}</div> : data ? <EmptyState title="All clear for now" detail="No attention signals are active." /> : <ChartLoading />}<div className="prototype-note"><Sparkles size={14} /><span>Pattern matching is a prototype signal, not a safety decision.</span></div></section></div>
  </>;
}

function Metric({ icon: Icon, label, value, note, tone }) {
  return <article className={`metric-card metric-${tone}`}><div className="metric-top"><span className="metric-icon"><Icon size={18} /></span><span className="metric-period">DEMO</span></div><div className="metric-value">{value ?? <i className="skeleton skeleton-value" />}</div><div className="metric-label">{label}</div><div className="metric-note">{note}</div></article>;
}
function ChartLoading() { return <div className="chart-loading"><span className="spinner" />Loading analytics</div>; }
