const reports = [
  { id: 'RPT-26165-001', title: 'Unprotected work at height', description: 'A maintenance worker was observed on an elevated platform without a connected fall-arrest lanyard. The task was paused and the area secured.', location: 'North process unit', activity: 'Elevated maintenance', date: '2026-09-29', reporterType: 'Supervisor', category: 'Working at Height', status: 'Under Review', analysis: { classification: 'Unsafe Condition', sif_precursor: true, risk_level: 'Critical', confidence: 0.96, hazards: ['Working at Height', 'Fall Protection'], entities: ['maintenance worker', 'elevated platform'], life_saving_rule: 'Working at Height', explanation: 'Work at height was observed without a connected fall-arrest system.', provider: 'Prototype NLP / Rule-based Analysis' } },
  { id: 'RPT-26165-002', title: 'Isolation point not verified', description: 'During pump maintenance, the equipment isolation had not been independently verified before work began. Work stopped until zero energy was confirmed.', location: 'Utilities block', activity: 'Pump maintenance', date: '2026-09-28', reporterType: 'Operator', category: 'Energy Isolation', status: 'Action Required', analysis: { classification: 'Unsafe Condition', sif_precursor: true, risk_level: 'Critical', confidence: 0.94, hazards: ['Energy Isolation', 'Unexpected Start-up'], entities: ['pump', 'maintenance crew'], life_saving_rule: 'Energy Isolation', explanation: 'The isolation was not verified before maintenance, creating an unexpected-energy exposure.', provider: 'Prototype NLP / Rule-based Analysis' } },
  { id: 'RPT-26165-003', title: 'Worker inside suspended-load zone', description: 'A pedestrian crossed beneath a suspended pipe spool during a lift. The signal person stopped the lift and redirected foot traffic.', location: 'Fabrication yard', activity: 'Pipe spool lifting', date: '2026-09-27', reporterType: 'Contractor', category: 'Line of Fire', status: 'In Progress', analysis: { classification: 'Near Miss', sif_precursor: true, risk_level: 'High', confidence: 0.91, hazards: ['Line of Fire', 'Lifting Operations'], entities: ['pedestrian', 'pipe spool', 'signal person'], life_saving_rule: 'Line of Fire', explanation: 'A person entered the drop zone beneath a suspended load.', provider: 'Prototype NLP / Rule-based Analysis' } },
  { id: 'RPT-26165-004', title: 'Gas test delayed before entry', description: 'A confined-space entry team waited at the vessel hatch because the required pre-entry gas test had not been completed.', location: 'Tank farm', activity: 'Vessel inspection', date: '2026-09-26', reporterType: 'Safety Representative', category: 'Confined Space', status: 'Under Review', analysis: { classification: 'Unsafe Condition', sif_precursor: true, risk_level: 'High', confidence: 0.89, hazards: ['Confined Space', 'Atmospheric Hazard'], entities: ['entry team', 'vessel hatch'], life_saving_rule: 'Confined Space', explanation: 'Entry was pending without a required pre-entry atmosphere test.', provider: 'Prototype NLP / Rule-based Analysis' } },
  { id: 'RPT-26165-005', title: 'Forklift and pedestrian near miss', description: 'A forklift reversed from a loading bay as a pedestrian entered the marked route. The spotter alerted both and no contact occurred.', location: 'Warehouse loading bay', activity: 'Material movement', date: '2026-09-25', reporterType: 'Operator', category: 'Vehicle Movement', status: 'Action Required', analysis: { classification: 'Near Miss', sif_precursor: true, risk_level: 'High', confidence: 0.9, hazards: ['Vehicle Movement', 'Line of Fire'], entities: ['forklift', 'pedestrian', 'loading bay'], life_saving_rule: 'Driving', explanation: 'A reversing vehicle and pedestrian came into conflict on a shared route.', provider: 'Prototype NLP / Rule-based Analysis' } },
  { id: 'RPT-26165-006', title: 'Load shifted during hoisting', description: 'A suspended bundle shifted when one sling moved out of position. The lift was halted, the exclusion zone remained clear, and the rigging was reset.', location: 'Pipe rack east', activity: 'Hoisting materials', date: '2026-09-24', reporterType: 'Rigger', category: 'Lifting Operations', status: 'In Progress', analysis: { classification: 'Near Miss', sif_precursor: true, risk_level: 'High', confidence: 0.88, hazards: ['Lifting Operations', 'Dropped Objects'], entities: ['bundle', 'sling', 'rigger'], life_saving_rule: 'Lifting Operations', explanation: 'A sling shifted during a lift, creating a dropped-load potential.', provider: 'Prototype NLP / Rule-based Analysis' } },
  { id: 'RPT-26165-007', title: 'Hot-work screen had a gap', description: 'Welding sparks passed through a gap in the fire-resistant screen. The hot work stopped while the screen was repositioned and the area checked.', location: 'Workshop bay 3', activity: 'Welding repair', date: '2026-09-23', reporterType: 'Welder', category: 'Hot Work', status: 'Completed', analysis: { classification: 'Unsafe Condition', sif_precursor: true, risk_level: 'Medium', confidence: 0.86, hazards: ['Hot Work', 'Fire'], entities: ['welding sparks', 'fire-resistant screen'], life_saving_rule: 'Hot Work', explanation: 'An incomplete spark screen weakened the hot-work fire controls.', provider: 'Prototype NLP / Rule-based Analysis' } },
  { id: 'RPT-26165-008', title: 'Damaged handrail reported', description: 'A section of handrail on the access walkway was loose. No one was injured; the walkway was cordoned off and a repair request was raised.', location: 'Admin access walkway', activity: 'Routine inspection', date: '2026-09-22', reporterType: 'Employee', category: 'Unsafe Condition', status: 'Completed', analysis: { classification: 'Unsafe Condition', sif_precursor: false, risk_level: 'Low', confidence: 0.78, hazards: ['Access and Egress'], entities: ['handrail', 'access walkway'], life_saving_rule: null, explanation: 'A loose handrail is an unsafe condition; no immediate SIF precursor indicator was identified.', provider: 'Prototype NLP / Rule-based Analysis' } },
  { id: 'RPT-26165-009', title: 'Tool briefly left in walk path', description: 'A technician noticed a portable tool in a walkway and moved it to the designated storage area before anyone tripped.', location: 'Control room corridor', activity: 'Inspection rounds', date: '2026-09-21', reporterType: 'Technician', category: 'Near Miss', status: 'Completed', analysis: { classification: 'Near Miss', sif_precursor: false, risk_level: 'Low', confidence: 0.83, hazards: ['Slip, Trip and Fall'], entities: ['portable tool', 'walkway', 'technician'], life_saving_rule: null, explanation: 'The obstruction was removed before an injury or high-consequence exposure occurred.', provider: 'Prototype NLP / Rule-based Analysis' } },
  { id: 'RPT-26165-010', title: 'Guard interlock bypass attempt', description: 'A machine guard interlock had been bypassed during troubleshooting. The machine was isolated and the bypass removed before restart.', location: 'Maintenance shop', activity: 'Machine troubleshooting', date: '2026-09-20', reporterType: 'Maintenance Lead', category: 'Safety Control Bypass', status: 'Action Required', analysis: { classification: 'Unsafe Act', sif_precursor: true, risk_level: 'Critical', confidence: 0.95, hazards: ['Safety Control Bypass', 'Caught In / Between'], entities: ['machine guard interlock', 'maintenance team'], life_saving_rule: 'Bypassing Safety Controls', explanation: 'A machine safety interlock was bypassed, defeating a critical protective control.', provider: 'Prototype NLP / Rule-based Analysis' } }
];

const actions = [
  { id: 'ACT-001', reportId: 'RPT-26165-001', action: 'Provide and verify fall-arrest equipment before elevated work resumes', owner: 'Maintenance Supervisor', dueDate: '2026-10-02', priority: 'Critical', status: 'Open' },
  { id: 'ACT-002', reportId: 'RPT-26165-002', action: 'Reinforce independent zero-energy verification for maintenance isolation', owner: 'Utilities Lead', dueDate: '2026-10-01', priority: 'High', status: 'In Progress' },
  { id: 'ACT-003', reportId: 'RPT-26165-003', action: 'Refresh lift exclusion-zone briefing with yard crews', owner: 'Lifting Coordinator', dueDate: '2026-10-04', priority: 'High', status: 'Open' },
  { id: 'ACT-004', reportId: 'RPT-26165-005', action: 'Review pedestrian and forklift segregation at loading bay', owner: 'Warehouse Lead', dueDate: '2026-10-03', priority: 'High', status: 'In Progress' },
  { id: 'ACT-005', reportId: 'RPT-26165-007', action: 'Inspect hot-work screens and update the setup checklist', owner: 'Workshop Supervisor', dueDate: '2026-09-30', priority: 'Medium', status: 'Completed' }
];

module.exports = { reports, actions };